# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import QSize
from win32api import GetMonitorInfo, MonitorFromPoint

class Ui_Form(object):
    def setupUi(self, Form):
        # 初始化窗口自适应屏幕大小
        self.desktop = QtWidgets.QApplication.desktop()
        self.screenWidth = self.desktop.width()
        self.screenHeight = self.desktop.height()
        # 界面控件自适应屏幕比例防止变形, 只有具体像素数值才使用
        self.rate = (self.screenWidth*self.screenHeight)/(1920*1080)
        # 获取win10任务栏高度
        monitor_info = GetMonitorInfo(MonitorFromPoint((0, 0)))
        work_area = monitor_info.get("Work")
        monitor_area = monitor_info.get("Monitor")
        self.work_height = monitor_area[3] - work_area[3]
        # 获取pyqt5主窗口标题栏高度
        self.title_height = 20
        Form.setObjectName("Form")
        Form.resize(self.screenWidth, self.screenHeight)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        # win10底部任务栏占据屏幕宽度
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, int(self.screenWidth*0.09), int(self.screenHeight-self.work_height-self.title_height)))
        self.verticalLayoutWidget.setStyleSheet("background-color:#002c41")
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        # 按钮图标大小
        self.icon_size = QSize(int(50*self.rate), int(50*self.rate))
        # 按钮大小自适应
        self.btnstyle = "QPushButton{text-align:center;color:rgb(240,240,240);font-family:'微软雅黑';font-size:22px;border-color:gray}"
        self.btnstyle.replace("22", str(int(22*self.rate)))
        self.button_Adaptive = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.pushButton_model = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_model.setStyleSheet(self.btnstyle)
        self.pushButton_model.setIcon(QIcon("icon/model.png"))
        self.pushButton_model.setIconSize(self.icon_size)
        self.pushButton_model.setSizePolicy(self.button_Adaptive)
        self.pushButton_model.setObjectName("pushButton_model")
        self.verticalLayout.addWidget(self.pushButton_model)
        self.pushButton_image = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_image.setStyleSheet(self.btnstyle)
        self.pushButton_image.setIcon(QIcon("icon/image.png"))
        self.pushButton_image.setIconSize(self.icon_size)
        self.pushButton_image.setSizePolicy(self.button_Adaptive)
        self.pushButton_image.setObjectName("pushButton_image")
        self.verticalLayout.addWidget(self.pushButton_image)
        self.pushButton_point = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_point.setStyleSheet(self.btnstyle)
        self.pushButton_point.setIcon(QIcon("icon/point.png"))
        self.pushButton_point.setIconSize(self.icon_size)
        self.pushButton_point.setSizePolicy(self.button_Adaptive)
        self.pushButton_point.setObjectName("pushButton_point")
        self.verticalLayout.addWidget(self.pushButton_point)
        self.pushButton_curve = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_curve.setStyleSheet(self.btnstyle)
        self.pushButton_curve.setIcon(QIcon("icon/curve.png"))
        self.pushButton_curve.setIconSize(self.icon_size)
        self.pushButton_curve.setSizePolicy(self.button_Adaptive)
        self.pushButton_curve.setObjectName("pushButton_curve")
        self.verticalLayout.addWidget(self.pushButton_curve)
        self.pushButton_config = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_config.setStyleSheet(self.btnstyle)
        self.pushButton_config.setIcon(QIcon("icon/config.png"))
        self.pushButton_config.setIconSize(self.icon_size)
        self.pushButton_config.setSizePolicy(self.button_Adaptive)
        self.pushButton_config.setObjectName("pushButton_config")
        self.verticalLayout.addWidget(self.pushButton_config)
        self.pushButton_align = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_align.setStyleSheet(self.btnstyle)
        self.pushButton_align.setIcon(QIcon("icon/align.png"))
        self.pushButton_align.setIconSize(self.icon_size)
        self.pushButton_align.setSizePolicy(self.button_Adaptive)
        self.pushButton_align.setObjectName("pushButton_align")
        self.verticalLayout.addWidget(self.pushButton_align)
        self.pushButton_exit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_exit.setStyleSheet(self.btnstyle)
        self.pushButton_exit.setIcon(QIcon("icon/exit.png"))
        self.pushButton_exit.setIconSize(self.icon_size)
        self.pushButton_exit.setSizePolicy(self.button_Adaptive)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.verticalLayout.addWidget(self.pushButton_exit)
        self.pushButton_geometry = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_geometry.setStyleSheet(self.btnstyle)
        self.pushButton_geometry.setIcon(QIcon("icon/geometry.png"))
        self.pushButton_geometry.setIconSize(self.icon_size)
        self.pushButton_geometry.setSizePolicy(self.button_Adaptive)
        self.pushButton_geometry.setObjectName("pushButton_geometry")
        self.verticalLayout.addWidget(self.pushButton_geometry)
        self.pushButton_save = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_save.setStyleSheet(self.btnstyle)
        self.pushButton_save.setIcon(QIcon("icon/save.png"))
        self.pushButton_save.setIconSize(self.icon_size)
        self.pushButton_save.setSizePolicy(self.button_Adaptive)
        self.pushButton_save.setObjectName("pushButton_save")
        self.verticalLayout.addWidget(self.pushButton_save)
        self.pushButton_query = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_query.setStyleSheet(self.btnstyle)
        self.pushButton_query.setIcon(QIcon("icon/query.png"))
        self.pushButton_query.setIconSize(self.icon_size)
        self.pushButton_query.setSizePolicy(self.button_Adaptive)
        self.pushButton_query.setObjectName("pushButton_query")
        self.verticalLayout.addWidget(self.pushButton_query)
        # 图片显示区域容器
        self.box_image = QtWidgets.QGroupBox(Form)
        self.box_image.setStyleSheet("background:#001b28")
        self.box_image.setGeometry(QtCore.QRect(int(self.screenWidth*0.09), 0, int(self.screenWidth*0.91), int(self.screenHeight)))
        # 图片显示区域
        self.label_image = QtWidgets.QLabel(self.box_image)
        # self.label_image.setStyleSheet("QLabel{background:black}")
        self.label_image.setGeometry(QtCore.QRect(0, 0, int(self.screenWidth*0.91), int(self.screenHeight)))
        self.label_image.setText("")
        # 居中显示图片
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")

        self.retranslateUi(Form)
        self.pushButton_model.clicked.connect(Form.btnOpenModel)
        self.pushButton_image.clicked.connect(Form.btnOpenImage)
        self.pushButton_point.clicked.connect(Form.btnKeyPoint)
        self.pushButton_curve.clicked.connect(Form.btnFitCurve)
        self.pushButton_config.clicked.connect(Form.btnOpenConfig)
        self.pushButton_align.clicked.connect(Form.btnAlignPoint)
        self.pushButton_exit.clicked.connect(Form.btnExitAlter)
        self.pushButton_geometry.clicked.connect(Form.btnMeasureGeometry)
        self.pushButton_save.clicked.connect(Form.btnSaveData)
        self.pushButton_query.clicked.connect(Form.btnQueryData)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "X光片关键点检测"))
        self.pushButton_model.setText(_translate("Form", "选择模型"))
        self.pushButton_image.setText(_translate("Form", "打开图片"))
        self.pushButton_point.setText(_translate("Form", "生成关键点"))
        self.pushButton_curve.setText(_translate("Form", "拟合曲线"))
        self.pushButton_config.setText(_translate("Form", "配置曲线"))
        self.pushButton_align.setText(_translate("Form", "编辑点位"))
        self.pushButton_exit.setText(_translate("Form", "退出编辑"))
        self.pushButton_geometry.setText(_translate("Form", "几何测量"))
        self.pushButton_save.setText(_translate("Form", "保存数据"))
        self.pushButton_query.setText(_translate("Form", "查询病例"))
